### ISSUE TITLE
Index Error while using @pytest.mark.xray decorator

### ISSUE THREAD

**Issue by abubakarafzal** [fundakol/pytest-jira-xray#101]
```
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvBamboo/lib/python3.12/site-packages/pytest_xray/xray_plugin.py", line 170, in pytest_collection_modifyitems
INTERNALERROR>     self._verify_jira_ids_for_items(items)
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvBamboo/lib/python3.12/site-packages/pytest_xray/xray_plugin.py", line 84, in _verify_jira_ids_for_items
INTERNALERROR>     test_keys = self._get_test_keys(item)
INTERNALERROR>                 ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/ronaldo/openC/ui-testspom/Tests_Bamboo_v2/venvBamboo/lib/python3.12/site-packages/pytest_xray/xray_plugin.py", line 70, in _get_test_keys
INTERNALERROR>     if isinstance(marker.args[0], str):
INTERNALERROR>                   ~~~~~~~~~~~^^^
INTERNALERROR> IndexError: tuple index out of range
```
    @pytest.mark.xray([
        'AR-7645',
        'AR-7406'
    ])
    def test_asd():

The mark.xray getting exception it doesnt work with list nor with single string. 

    @pytest.mark.xray(
        'AR-7645')

there is an issue in the method in class xray_plugin
```
   def _get_test_keys(self, item: Item) -> List[str]:
        """Return JIRA ids associated with test item"""
        test_keys: List[str] = []
        marker = self._get_xray_marker(item)

        if not marker:
            return test_keys

        if isinstance(marker.args[0], str):
            test_keys = [marker.args[0]]
        elif isinstance(marker.args[0], list):
            test_keys = list(marker.args[0])
        else:
            raise XrayError('xray marker can only accept strings or lists')
        return test_keys
```

**Comment by abubakarafzal** [comment]
@fundakol are you guys actively supporting this Repo/Plugin

**Comment by fundakol** [comment]
It does work for me. Can you share what packages you have installed?

**Comment by abubakarafzal** [comment]
[requirements.txt](https://github.com/fundakol/pytest-jira-xray/files/14780189/requirements.txt)
here its my packages i have installed

**Comment by fundakol** [comment]
Check if you have a test decorated like so:
```python
@pytest.mark.xray
def test_foo():
   pass
```
This won't work.

**Comment by abubakarafzal** [comment]
```
    @pytest.mark.demo
    @pytest.mark.xray('AR-7645')
    def test_my_function(self):
        # Your test code here
        pass 
```
here is my decorator

**Comment by fundakol** [comment]
Can you install this plugin from the branch `pip install git+https://github.com/fundakol/pytest-jira-xray.git@improve-handling-errors`
It will show which test is broken.

**Comment by abubakarafzal** [comment]
what i dont changed this method from xray_plugin file to 
from:
```
def _get_test_keys(self, item: Item) -> List[str]:
        """Return JIRA ids associated with test item"""
        test_keys: List[str] = []
        marker = self._get_xray_marker(item)

        if not marker:
            return test_keys

        if isinstance(marker.args[0], str):
            test_keys = [marker.args[0]]
        elif isinstance(marker.args[0], list):
            test_keys = list(marker.args[0])
        else:
            raise XrayError('xray marker can only accept strings or lists')
        return test_keys
```

to this and it works
```
    def _get_test_keys(self, item: Item) -> List[str]:
        """Return JIRA ids associated with test item"""
        test_keys: List[str] = []
        marker = self._get_xray_marker(item)
        if not marker or not marker.args:
            return test_keys

        if isinstance(marker.args[0], str):
            test_keys = [marker.args[0]]
        elif isinstance(marker.args[0], list):
            test_keys = list(marker.args[0])
        return test_keys
```

**Comment by fundakol** [comment]
That error which you have can happen only when you have xray marker without any argument, like `@pytest.mark.xray`. The change you proposed just silently ignores this wrong marker.

**Comment by abubakarafzal** [comment]
Yeah, ill look into it and can you let me know how can i pass the test plan id rather then execution id , 

And the executions should be created automatically into that test plan 
pytest --jira-xray --client-secret-auth --cloud --execution AR-9516 -m demo  --browser chrome_headless

**Comment by fundakol** [comment]
`pytest --jira-xray --testplan TestPlanId`, it will create new test execution for the test plan.

**Comment by abubakarafzal** [comment]
Thanks its working i am closing the Issue, the issue was it was overlapping with the plugin https://github.com/typhoon-hil/pytest-typhoon-xray i was using it before.

I removed it and commented out all my test cases which were using 
`@pytest.mark.xray(test_key='PRJ-123')
`
And it works you have done a great job Buddy

**Comment by abubakarafzal** [comment]
Resolved not an issue of the plugin it was my internal issue,

Thanks @fundakol
