### ISSUE TITLE
Bad Request on execution import

### ISSUE THREAD

**Issue by mreiche** [fundakol/pytest-jira-xray#18]
I just get the following error:

```
Could not publish results to Jira XRAY!
HTTPError: Could not post to JIRA service at https://example.com/jira/rest/raven/2.0/import/execution. Response status code: 400
```
when running the execution. The Base URL is fine, because I use it with official Jira python library. The code 400 means: Bad Request, how can I debug that?

**Comment by fundakol** [comment]
It could be test ID which does not exist in database, or user has no access to that test. 

This is error message which I have when I try to import results from web page:
```
Error importing execution results to database:

Test issue with key LES-99 not found.
```
From command line it is 400 with error: Error assembling issue data: project is required

**Comment by mreiche** [comment]
How do I configure the project?
