### ISSUE TITLE
Using plugin raises PytestUnknownMarkWarning

### ISSUE THREAD

**Issue by stefanoborini** [fundakol/pytest-jira-xray#26]
I get the following warnings: 

```
PytestUnknownMarkWarning: Unknown pytest.mark.xray - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
```

I always assumed that if the mark is declared in the plugin, you should not manually add it. Of course the workaround is trivial to do, but either I misunderstood how pytest should behave with plugin-provided markers, or something is preventing pytest from discovering the marker from the plugin.

**Comment by fundakol** [comment]
It is added, but only if your run tests with --jira-xray argument: https://github.com/fundakol/pytest-jira-xray/blob/master/src/pytest_xray/plugin.py#L102
I can fix this.
