### ISSUE TITLE
Xray Cloud - Statuses "PASS" and "FAIL" are not correct

### ISSUE THREAD

**Issue by apcapopa** [fundakol/pytest-jira-xray#30]
Following values are set in the json file:
"status": "FAIL"
or 
"status": "PASS"

Using these values, Test Cases status is set **TO DO**

[Xray documentation](https://docs.getxray.app/display/XRAYCLOUD/Import+Execution+Results+-+REST+v2#ImportExecutionResultsRESTv2-XrayJSONresults) specifies "PASSED" and "FAILED"

**Comment by apcapopa** [comment]
Is it that --xraypath=xray.json is using the server properties?

**Comment by fundakol** [comment]
Did you use `--cloud` parameters with your command?

**Comment by apcapopa** [comment]
Using the --cloud option generates the proper output.
Thanks!
