### ISSUE TITLE
Possibility to mark a test to satisfy two or more test identifiers?

### ISSUE THREAD

**Issue by stefanoborini** [fundakol/pytest-jira-xray#32]
The XRay format wants a string in the json file for the "testKey" entry. Example

     "testKey": "QSOL-1122"

However, it is not uncommon to me that some of my pytest tests check multiple xray tests. This is because I use pytest to run selenium, and it uses considerable time so it pays off to check multiple xray tests in a single pytest test.

I tried using

     @pytest.mark.xray(["QSOL-1234", "QSOL-1235"])

and pytest-jira-xray does create a json file with a list, instead of a string, in the "testKey". Unfortunately, Xray refuses to parse this format, requiring a string only for the "testKey".

I propose a modification in the behavior of the library, so that when it is passed a list, it will create two "testKey" entries (probably with the same evidence) to appease Xray, while giving the flexibility to implement this use case.

I can implement this in the library, but before doing so I want the issue to be known to the author. Once it's been discussed, I can implement the feature. Please let me know.

**Comment by fundakol** [comment]
I don't mind to extend functionality with this feature. If you have an idea how to implement it feel free to create a pull requests.

**Comment by stefanoborini** [comment]
@fundakol ok, I'll send you a PR in a few days. Thanks.
