### ISSUE TITLE
Could not publish results to Jira XRAY!

### ISSUE THREAD

**Issue by srihmallampati** [fundakol/pytest-jira-xray#42]
We have integrated this plugin into the git pipeline and when all the tests have ran we are getting below error - 
---------------------------------- Jira XRAY -----------------------------------
Could not publish results to Jira XRAY!
HTTPError: Could not post to JIRA service at https://xray.cloud.getxray.app/api/v2/import/execution. Response status code: 400

Below is the code used for the initial set-up on the Git yml file - 
# Set up Jira authentication for automatic Xray test execution update
  - export XRAY_API_BASE_URL=https://xray.cloud.getxray.app
  - export XRAY_CLIENT_ID=${XRAY_CLIENT_ID}
  - export XRAY_CLIENT_SECRET=${XRAY_CLIENT_SECRET}
  - pytest --alluredir report/allure/allure-results --jira-xray --execution TEST-xxxx --cloud
 
 Also, inside the code we are using some as below - 
 @pytest.mark.xray(['TEST-xxx', 'TEST-xx'])
def test1():

@pytest.mark.xray('TEST-')
def test2():

**Comment by fundakol** [comment]
Hi, I uploaded plugin in version 0.7.1 with improved printing errors returned from Jira server. Could you use that version and check what error you get?
