### ISSUE TITLE
Can't send results to Jira Cloud from Intellij

### ISSUE THREAD

**Issue by oldyew** [fundakol/pytest-jira-xray#43]
XRAY_API_BASE_URL, XRAY_API_PASSWORD and XRAY_API_USER are specified but I got next error
requests.exceptions.JSONDecodeError: [Errno Expecting value] Basic authentication with passwords is deprecated.

if I trying to use Jira API token or/and clientid/client_secret, I get the same error.

**Comment by fundakol** [comment]
It seems basic authentication with a password is deprecated https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

Did you try with an email as username and a token as password?

**Comment by fundakol** [comment]
I need to implement a token authentication for cloud server.

**Comment by oldyew** [comment]
I see. Thank you! Look forward to hearing from you!
