### ISSUE TITLE
Can't create new execution in XRAY cloud, using Jira client secret authentication

### ISSUE THREAD

**Issue by ormembar31** [fundakol/pytest-jira-xray#48]
I'm trying post to xray a new execution but I get:
[xray_publisher.py][ERROR] Error message from server: Error creating Test Execution - Issue create failed! - Field Assignee is required.

I'm using Jira cloud and I'm running with inteliJ and the following arguments:
 --jira-xray --cloud --client-secret-auth -o log_cli=true

**Comment by fundakol** [comment]
Do you have proper rights for an account which is used to upload results? 
I don't see any `assignee` filed in Rest API documentation https://docs.getxray.app/display/XRAY/v2.0#/Import/post-import-execution. Do you have some custom configuration in your Jira instance? 
Can you check if you can upload a results manually from Jira UI (generate results to file by param `--xraypath=xray.json` first)?

**Comment by ormembar31** [comment]
Thank you for the quick response.
I believe `assignee` is `user` field.
I didn't mention it before but I was able to **update** an existing execution with the `--execution TestExecutionId`. The existing execution had a user field so I guess that's why it succeeded.
I will try the manual test you suggested in the meantime

**Comment by ormembar31** [comment]
using `--xraypath=xray.json` produced the following JSON:
`{
  "info": {
    "startDate": "2022-08-02T06:24:57+0000",
    "finishDate": "2022-08-02T06:24:57+0000",
    "summary": "testing pytest-jira-xray plugin",
    "description": "testing working with pytest-jira-xray plugin"
  },
  "tests": [
    {
      "testKey": "DEMO-4961",
      "status": "PASSED",
      "comment": ""
    }
  ]
}`

**Comment by fundakol** [comment]
There is a field `user` in a report schema. It wasn't required for basic authentication because it was set be default to user from credentials on server site. But maybe it does not work anymore or does not work for client-secret-auth. I can fix this by setting `user` field same as `XRAY_API_USER` env variable or from command line e.g. `--xray-user`.

**Comment by fundakol** [comment]
I added pytest hook that allows to modify XRAY results before uploading. 
I can be used in conftest.py like so:
```python
def pytest_xray_results(results):
    results['info']['user'] = 'Jira user'
```
Can you verify on your side if it fixes your issue? 
The change is available on branch `implement-hook-to-modify-results` https://github.com/fundakol/pytest-jira-xray/tree/implement-hook-to-modify-results
(You can modify other fields as well as long as it follows XRAY schema)

**Comment by ormembar31** [comment]
It Works! Thank you for your quick reply and fix.
I have one question, now with the new hook, you can for example input the `summary` and the `description` either from the environment variables or from the hook. Is this a good behavior?

**Comment by fundakol** [comment]
Yes, you can modify/add any other filed from the hook. Probably it is more convenient then using environment variables.
