### ISSUE TITLE
Add the possibility to set custom JIRA web server truststore

### ISSUE THREAD

**Issue by h-rueda** [fundakol/pytest-jira-xray#5]
I am getting this error when executing my pytests :
`OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]`

Could you please allow the possibility to set the truststore of the JIRA web server ?

It coulb be a new environmental variable like :
`export XRAY_API_BASE_TRUSTSTORE=</path/to/PEM file> or False`

Then add the truststore parameter in the `requests.request` call

```
   def publish_xray_results(self, url: str, auth: AuthBase, data: dict) -> dict:
        headers = {'Accept': 'application/json',
                   'Content-Type': 'application/json'}
        data = json.dumps(data)
        try:
            response = requests.request(method='POST', url=url, headers=headers, data=data, auth=auth, verify=truststore)
```

**Comment by fundakol** [comment]
I introduced an implementation for SSL certificate verification in #7, but I am not able to test it. I would be grateful if you could verify it on your side.

**Comment by h-rueda** [comment]
It works fine :)
