### ISSUE TITLE
--allow-duplicate-ids flag is unclear in main page

### ISSUE THREAD

**Issue by ormembar31** [fundakol/pytest-jira-xray#53]
![image](https://user-images.githubusercontent.com/110335519/188806585-3b785dbb-9482-46fd-b086-dd28cf6ecfcf.png)

looking in github I see that the `--allow-duplicate-ids` is clear, but in the plugin's PYPI page the 2 hyphens look like 1 hyphen. 
perhaps put the flag in a gray example box

**Comment by fundakol** [comment]
Thanks for pointing that out, I will update readme file to improve it.

**Comment by globaldeepa** [comment]
Can you please provide more details to use this option in the command. somehow it is not working for me.

Thanks !
