### ISSUE TITLE
xfailed tests appear as failed in execution

### ISSUE THREAD

**Issue by ormembar31** [fundakol/pytest-jira-xray#58]
Tests marked as "xfail" in pytest appear as "failed" in test execution. Is this the correct behavior?
Is there an option to configure this behavior?

**Comment by fundakol** [comment]
There is not XFail status in Xray, so statu for pytest test, which failed and was marked as xfail, must be mapped to one of available status: `TODO`, `EXECUTING`, `PENDING`, `PASSED`, `FAILED`, `ABORTED`, `BLOCKED`. 
Would you like to have different status for those tests?

**Comment by ormembar31** [comment]
Is it possible to add a custom status to XRAY and map the xfailed tests to that status?

Also, I noticed the skipped tests are marked as TODO (which does make sense to me). We added to our XRAY a custom marker called `skipped`. So same question, can we map skipped tests to the custom status we created?

**Comment by fundakol** [comment]
Custom status makes sense only if no one else is using this plugin, but it must work with any instance of Xray server. 
But you can modify a report before it is sent to Xray using a hook, e.g.:
```python
# FILE: conftest.py
def pytest_xray_results(results, session):
    for test in results['tests']:
        if test['status'] == 'TODO':
           test['status'] = 'SKIP'
```

**Comment by ormembar31** [comment]
Thanks! 
The solution using the hook looks like a good option for me!
