### ISSUE TITLE
Alternative way to set test execution summary?

### ISSUE THREAD

**Issue by richardlthomas** [fundakol/pytest-jira-xray#66]
It seems strange that the required test execution summary is tied to an environment variable so that it is the same for every run unless I change the environment variable. Is there any way to pass it in as a flag or in a fixture or something?

**Comment by fundakol** [comment]
Have you tried with the hook?

```python
def pytest_xray_results(results, session):
    results['info']['summary'] = 'anything you want'
```

**Comment by richardlthomas** [comment]
Yep, I figured that out shortly after opening the issue. Mind if I make a PR to improve the documentation around what the hook can do?

**Comment by fundakol** [comment]
Feel free with any PR.
