### ISSUE TITLE
Start time is after finish time

### ISSUE THREAD

**Issue by AnnaWAceso** [fundakol/pytest-jira-xray#67]
When executing tests and exporting them to XRay, an error occurs as the Start date is set after the Finish date. This also happens when generating a .json file instead of directly exporting to the XRay and it confirmed when looking into the .json file that the "startDate" lies after the "finishDate", by one second.

{
  "info": {
    "startDate": "2023-02-08T12:40:25+0000",
    "finishDate": "2023-02-08T12:40:24+0000"
    }
(...)
}

**Comment by fundakol** [comment]
Fixed in 0.8.4
