### ISSUE TITLE
X-Ray Authentication failure due to SSL

### ISSUE THREAD

**Issue by addymeni** [fundakol/pytest-jira-xray#68]
Is it possible to also pass the ENV_XRAY_API_VERIFY_SSL parameter to the ClientSecretAuth class here - https://github.com/fundakol/pytest-jira-xray/blob/master/src/pytest_xray/xray_publisher.py#L40 that is advised here - https://github.com/psf/requests/issues/6071#issuecomment-1059528942 

OR 

What's the alternative to set it to False. I tried few methods like creating a fixture in conftest and setting session.verify in requests.Session() as False but didn't work. None of the solutions are able to set the SSL to false. Could you please advice?

**Comment by fundakol** [comment]
I created PR with a fix, could you check if it works for you? https://github.com/fundakol/pytest-jira-xray/pull/69

**Comment by addymeni** [comment]
@fundakol this works!!

**Comment by fundakol** [comment]
Released as 0.8.5

**Comment by addymeni** [comment]
Thank you!
