### ISSUE TITLE
Is there an option to get the execution id that created at the end of the run?

### ISSUE THREAD

**Issue by TehilaYisachar** [fundakol/pytest-jira-xray#8]

**Comment by fundakol** [comment]
Test execution id can be printed in terminal.

**Comment by Irinka73** [comment]
Tell me please. Is there a way to get an TestExecutionId for further work with it? I need to create a link for a new TestExecution to another issue in Jira.

**Comment by fundakol** [comment]
Try with this in `conftest.py`:
```python
@pytest.hookimpl(trylast=True)
def pytest_sessionfinish(self, session):
    xray_plugin = session.config.pluginmanager.getplugin('JIRA_XRAY')
    execution_id = xray_plugin.issue_id
```
It may work.

**Comment by Irinka73** [comment]
Yes, this code works.
thanks for the help
